CREATE TABLE scenario_bank (
    id         BIGSERIAL PRIMARY KEY,
    slot       SMALLINT NOT NULL,
    theme      VARCHAR(40) NOT NULL,
    text       VARCHAR(400) NOT NULL UNIQUE,
    uses       INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_scenario_bank_slot_uses ON scenario_bank (slot, uses);

INSERT INTO scenario_bank (slot, theme, text) VALUES
    (1, 'Real world', 'You are hiking alone when thick fog covers the mountain. You cannot see the path and the sun is going down.'),
    (1, 'Real world', 'You are driving at night when your car stops on an empty road. There is no phone signal and it starts to snow.'),
    (1, 'Real world', 'You are in a lift with five other people when the lights go out and the lift stops between two floors.'),
    (1, 'Real world', 'A big storm hits your camp at night. The river is rising fast and your tent starts to fill with water.'),
    (1, 'Real world', 'You are swimming at the beach when you see that you are far from the shore and the current keeps pulling you out.'),
    (1, 'Real world', 'You are on a small boat when the engine dies. The sun is going down and you cannot see land.'),
    (1, 'Real world', 'You are walking home when the whole city loses power. It is dark, cold and every street looks the same.'),
    (1, 'Real world', 'You are in a forest when you lose your map and your phone battery dies. It will be dark soon.'),
    (1, 'Real world', 'You are on a train in the desert when it breaks down. There is no air conditioning and the heat is very strong.'),
    (1, 'Real world', 'Heavy rain floods the street and your car begins to float. The water is rising fast around you.'),
    (1, 'Real world', 'You are in a shopping mall when the ground begins to shake. People are running and the lights are flickering.'),
    (1, 'Real world', 'You are skiing when a snow storm hides the slope. You cannot tell which way is down and you are alone.'),
    (1, 'Real world', 'You wake up at night and smell smoke. Your room is filling with it and the door handle is hot.'),
    (1, 'Real world', 'You are on the roof of a house in a flood. The water is still rising and the boats have not come yet.'),
    (1, 'Real world', 'You are lost in a big cave after your torch stops working. You can hear water somewhere in the dark.'),
    (1, 'Real world', 'You are camping when a bear walks into your camp. It is looking at your food and it is only a few steps away.'),
    (1, 'Real world', 'Your plane lands on a lonely island after an emergency. You have a small bag and a bottle of water.'),
    (1, 'Real world', 'You are in a small boat when a storm starts. The waves are as tall as the boat and rain is everywhere.'),
    (1, 'Real world', 'You are outside on a very hot day with no water. The nearest shop is many hours away.'),
    (1, 'Real world', 'You are in an old building when the floor begins to break. Half of the stairs are gone and it is getting worse.'),
    (2, 'Comedy', 'A group of very angry geese is chasing you through the park. They are fast, loud and they want your sandwich.'),
    (2, 'Comedy', 'A giant round cheese is rolling down the hill straight at you. It is getting faster and it smells very strong.'),
    (2, 'Comedy', 'You are at a wedding when the cake falls on the floor. Everyone looks at you and the bride starts to cry.'),
    (2, 'Comedy', 'You are at a job interview when your chair breaks. The boss asks you a hard question while you lie on the floor.'),
    (2, 'Comedy', 'You are meeting your partner''s parents for dinner and you sit on the family cat. The cat is very angry.'),
    (2, 'Comedy', 'You are stuck inside a giant bouncy castle that is slowly filling with air. The walls are getting closer.'),
    (2, 'Comedy', 'You are on stage in a talent show when you forget your act. Two thousand people are waiting and the lights are hot.'),
    (2, 'Comedy', 'A seagull steals your ice cream and now a hundred more seagulls are coming for you.'),
    (2, 'Comedy', 'You are in a tiny lift with your boss when you let out a very loud sneeze. Your boss is not happy.'),
    (2, 'Comedy', 'Your dog ate your homework, your keys and your phone. Now it is running away with your shoe.'),
    (2, 'Comedy', 'You are at a fancy dinner when you see that you are wearing two different shoes and everyone is looking.'),
    (2, 'Comedy', 'You fall into a pool of jelly at a party and you cannot get out. Every move makes you sink more.'),
    (2, 'Comedy', 'You are on a cooking show and the oven starts to make strange noises. The judge is watching and smiling.'),
    (2, 'Comedy', 'A monkey took your bag at the zoo. It is now sitting in a tall tree and eating your lunch.'),
    (2, 'Comedy', 'You are on a first date when the waiter brings a huge bill. Your wallet is missing and your date is watching.'),
    (2, 'Comedy', 'You are riding a bike with no brakes down a hill straight toward a market full of eggs.'),
    (2, 'Comedy', 'You are at the airport when your bag opens. Everything falls out and your funny underwear rolls across the floor.'),
    (2, 'Comedy', 'You are at a party when you find out that everyone is wearing the same costume as you and nobody knows who is who.'),
    (2, 'Comedy', 'A duck follows you into a fancy shop and starts to make loud noises. The manager is very angry.'),
    (2, 'Comedy', 'Your phone starts to play a very loud song during a quiet meeting. You cannot find the button to stop it.'),
    (3, 'Imagination', 'A dragon lands in front of you and asks you to give it your lunch. It looks hungry and angry.'),
    (3, 'Imagination', 'You walk into a magic forest when the trees begin to move and close the path behind you.'),
    (3, 'Imagination', 'A wizard turns your friends into frogs and now he is looking at you with his magic stick.'),
    (3, 'Imagination', 'You are alone on a space station when the lights turn red. A strange green cloud is coming through the walls.'),
    (3, 'Imagination', 'Aliens land in your garden and say they will take one human to their planet. They are looking at you.'),
    (3, 'Imagination', 'A friendly robot in your house suddenly stops listening to you and locks all the doors.'),
    (3, 'Imagination', 'Zombies are walking toward your house, but they move very slowly and they are singing old songs.'),
    (3, 'Imagination', 'You wake up in a haunted house and every door leads back to the same room. The ghost is laughing.'),
    (3, 'Imagination', 'A giant spider the size of a bus is building a web across your street. Your car is stuck in it.'),
    (3, 'Imagination', 'You are in a castle when the floor opens and you fall into a room full of sleeping trolls.'),
    (3, 'Imagination', 'Your time machine is broken. It keeps jumping to different years and a dinosaur is chasing you.'),
    (3, 'Imagination', 'A vampire invites you to dinner, and you are the only person at the table with no plate.'),
    (3, 'Imagination', 'You are a knight and your sword just turned into a banana. A big dragon is walking toward you.'),
    (3, 'Imagination', 'You are on a spaceship when the computer says it will turn off the air in ten minutes to save power.'),
    (3, 'Imagination', 'You find a magic lamp, but the genie is grumpy and says it will give you one wish and take one thing away.'),
    (3, 'Imagination', 'A giant sea monster rises next to your small boat. It has a hat on its head and looks very hungry.'),
    (3, 'Imagination', 'You are on a planet where the ground is made of sticky glue and a large alien is running toward you.'),
    (3, 'Imagination', 'Your school turns into a haunted castle at midnight. The teachers are now ghosts and they are giving out tests.'),
    (3, 'Imagination', 'A friendly witch gives you some soup, but the soup can talk and it says do not drink me.'),
    (3, 'Imagination', 'A group of tiny elves is stealing all of your things and they are much faster than you.'),
    (4, 'Weird', 'Gravity suddenly turns off and you float up into the sky. The city is getting smaller and smaller below you.'),
    (4, 'Weird', 'You are in a city made of jelly. Every step makes the ground shake and the buildings are starting to melt.'),
    (4, 'Weird', 'You shrink to the size of an ant in the middle of a kitchen. A cat is walking toward you.'),
    (4, 'Weird', 'You wake up as big as a house, and the people in the street are the size of ants.'),
    (4, 'Weird', 'It starts to rain, but the rain is thick soup. It is getting deeper and it is very hot.'),
    (4, 'Weird', 'All the clocks in the world stop and everything goes slow, except for a hungry bear that runs at normal speed.'),
    (4, 'Weird', 'You are in a dream where the floor is a giant trampoline and each jump sends you higher into a dark sky.'),
    (4, 'Weird', 'You walk through a door and enter a world where everything is upside down, even the sky.'),
    (4, 'Weird', 'You are inside a video game and you have only one life left. A huge boss is coming for you.'),
    (4, 'Weird', 'Your shadow comes alive and starts to run away with all your things. It is faster than you.'),
    (4, 'Weird', 'You fall into a bowl of cereal and the milk is rising. A giant spoon is coming down from the sky.'),
    (4, 'Weird', 'The whole world turns into a giant board game, and you are a small piece that must not be knocked over.'),
    (4, 'Weird', 'You are inside a giant washing machine and the water is coming in. The door is very far away.'),
    (4, 'Weird', 'Every person in the city swaps voices with an animal. A cow is shouting and a dog is crying.'),
    (4, 'Weird', 'You are standing on a cloud that is slowly melting. The ground is very far below you.'),
    (4, 'Weird', 'You shrink to the size of a coin and fall into a busy street full of shoes.'),
    (4, 'Weird', 'You wake up inside a giant cake and a hungry giant is holding a fork next to you.'),
    (4, 'Weird', 'Colors are disappearing from the world one by one and the dark shapes that come after them are hungry.'),
    (4, 'Weird', 'You are in a room where the walls slowly move closer. All the doors are only pictures on the walls.'),
    (4, 'Weird', 'The moon comes down close to the earth and starts to pull everything up into the sky, including you.'),
    (5, 'Finale', 'A giant monster is walking through your city. It is breaking buildings, and it is looking straight at your street.'),
    (5, 'Finale', 'The sun starts to go out. The air is getting colder each minute and only the moon gives some light.'),
    (5, 'Finale', 'You are on a pirate ship on the moon when a giant space octopus grabs the ship with its arms.'),
    (5, 'Finale', 'A dinosaur crashes a wedding, and the bride and groom run away. Only you are left and it is hungry.'),
    (5, 'Finale', 'A huge wave, taller than a mountain, is coming toward your town. You can hear it roar.'),
    (5, 'Finale', 'The world begins to fall apart. Big holes open in the ground and everything is slowly falling into them.'),
    (5, 'Finale', 'Robots take over the city, and the only place with no robots is an old school where you are hiding.'),
    (5, 'Finale', 'You are inside a volcano when it begins to wake up. The lava is coming up and the exit is very far.'),
    (5, 'Finale', 'A giant robot and a giant lizard begin to fight right above your house. Big rocks are falling everywhere.'),
    (5, 'Finale', 'You are a cowboy on Mars and a herd of angry space cows is running toward you.'),
    (5, 'Finale', 'A time storm is mixing the past and the future. Knights, robots and dinosaurs are all running down your street.'),
    (5, 'Finale', 'You are on a sinking spaceship in an ocean of chocolate and the sharks are made of candy.'),
    (5, 'Finale', 'The whole earth begins to shake and the sky turns purple. A giant hand comes out of the clouds.'),
    (5, 'Finale', 'You are a chef in a castle when a dragon says it will burn the kitchen unless you make the best pizza in the world in ten minutes.'),
    (5, 'Finale', 'A giant wave of popcorn is rolling down the street, and you are on a skateboard with no way to stop.'),
    (5, 'Finale', 'Ninjas and pirates are having a huge fight in your school, and both sides think you have the treasure.'),
    (5, 'Finale', 'The ground opens and a very tall tower rises up. At the top a robot king is waiting for you.'),
    (5, 'Finale', 'You are the last person on earth, and all the animals have become giant and are holding a meeting about you.'),
    (5, 'Finale', 'A black hole is coming closer to earth. It pulls things in one by one and your house is next.'),
    (5, 'Finale', 'You are in a race across the sky with a hundred flying cars, and your car is on fire.');
